model_name_or_path: /root/autodl-tmp/comp/LLaMA-Factory/Qwen3-Coder-30B-A3B-Instruct

stage: sft

dataset: bird_mini_text2sql
dataset_dir: data

template: qwen
finetuning_type: lora

lora_rank: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target: q_proj,k_proj,v_proj,o_proj

per_device_train_batch_size: 2
gradient_accumulation_steps: 4
num_train_epochs: 3
learning_rate: 1.0e-4
lr_scheduler_type: cosine
warmup_ratio: 0.03
max_grad_norm: 1.0

cutoff_len: 2048

output_dir: saves/qwen3-coder-30b/lora/bird_sft
logging_steps: 10
save_steps: 200
save_total_limit: 3

bf16: true
gradient_checkpointing: true
ddp_find_unused_parameters: false
